[build]
  publish = "."

[build.processing]
  skip_processing = false

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "index.html"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
